module.exports = [
  {
    id: 1,
    stringId: "mystic-seer",
    name: "Mystic Seer",
    avatarUrl: { file_url: "images/mystic.gif" },
    description: "A wise and powerful seer with the power of Thunderbolt.",
    health: 80,
    strength: 10,
    attack: 10,
    speed: 10,
    super_power: "Thunderbolt",
    file_url: "/models/mystic.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 317,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_MYSTIC",
    playerId: "PLAYER_ID_MYSTIC",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 2,
    stringId: "zylar-the-conqueror",
    name: "Zylar the Conqueror",
    avatarUrl: { file_url: "images/zylar.gif" },
    description: "A mighty warrior with the power to unleash a Flamethrower.",
    health: 90,
    strength: 10,
    attack: 13,
    speed: 9,
    super_power: "Flamethrower",
    file_url: "/models/zylar.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 385,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_ZYLAR",
    playerId: "PLAYER_ID_ZYLAR",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 3,
    stringId: "shadow-strike",
    name: "Shadow Strike",
    avatarUrl: { file_url: "images/s-strike.gif" },
    description: "A swift and stealthy fighter who strikes from the shadows.",
    health: 75,
    strength: 10,
    attack: 13,
    speed: 10,
    super_power: "VineWhip",
    file_url: "/models/s-strike.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 307,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_STRIKE",
    playerId: "PLAYER_ID_STRIKE",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 4,
    stringId: "captain-valor",
    name: "Captain Valor",
    avatarUrl: { file_url: "images/c-valor.gif" },
    description: "A heroic warrior with the power of WaterGun.",
    health: 85,
    strength: 8,
    attack: 10,
    speed: 8,
    super_power: "WaterGun",
    file_url: "/models/c-valor.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 350,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_VALOR",
    playerId: "PLAYER_ID_VALOR",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 5,
    stringId: "sir-elara-the-great",
    name: "Sir Elara the Great",
    avatarUrl: { file_url: "images/s-elara.gif" },
    description: "A knight who commands the fire and can unleash a fireball.",
    health: 95,
    strength: 12,
    attack: 15,
    speed: 9,
    super_power: "Fireball",
    file_url: "/models/s-elara.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 400,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_EMPRESS",
    playerId: "PLAYER_ID_EMPRESS",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 6,
    stringId: "ghoul-king",
    name: "Ghoul King",
    avatarUrl: { file_url: "images/ghoul.gif" },
    description:
      "A speedster who uses the power of the storm to ride and defeat.",
    health: 85,
    strength: 10,
    attack: 12,
    speed: 15,
    super_power: "Thunderstorm",
    file_url: "/models/ghoul.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 370,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_STORMRIDER",
    playerId: "PLAYER_ID_STORMRIDER",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 7,
    stringId: "elinor-swiftstrike",
    name: "Elinor Swiftstrike",
    avatarUrl: { file_url: "images/e-swiftstrike.gif" },
    description: "A giant of the earth with immense strength and defense.",
    health: 120,
    strength: 15,
    attack: 12,
    speed: 7,
    super_power: "Earthquake",
    file_url: "/models/e-swiftstrike.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 420,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_TERRATITAN",
    playerId: "PLAYER_ID_TERRATITAN",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 8,
    stringId: "ravager",
    name: "Ravager",
    avatarUrl: { file_url: "images/ravager.gif" },
    description:
      "A knight with the power of the moon to shine bright in battle.",
    health: 100,
    strength: 10,
    attack: 14,
    speed: 10,
    super_power: "SonicKick",
    file_url: "/models/ravager.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 380,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_LUNARKNIGHT",
    playerId: "PLAYER_ID_LUNARKNIGHT",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 9,
    stringId: "bone-collector",
    name: "Bone Collector",
    avatarUrl: { file_url: "images/b-collector.gif" },
    description:
      "A fierce dragon capable of devastating its enemies with flame.",
    health: 110,
    strength: 14,
    attack: 15,
    speed: 8,
    super_power: "TelekineticHit",
    file_url: "/models/b-collector.glb",
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 460,
    owner: "677d1b6f4cc2b488494a2b7e",
    mintAddress: "MINT_ADDRESS_DRAGONFURY",
    playerId: "PLAYER_ID_DRAGONFURY",
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 10,
    stringId: 'vortex',
    name: 'Vortex',
    avatarUrl: { file_url: "images/vortex.gif" },
    description: 'A knight blessed with the power of the cosmos to shield allies and strike foes.',
    health: 105,
    strength: 13,
    attack: 12,
    speed: 9,
    super_power: 'SonicKick',
    file_url: '/models/vortex.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 450,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_COSMICKNIGHT',
    playerId: 'PLAYER_ID_COSMICKNIGHT',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 11,
    stringId: 'dire-wolf',
    name: 'Dire Wolf',
    avatarUrl: { file_url: "images/d-wolf.gif" },
    description: 'An archer who commands the vortex winds to guide her arrows with precision.',
    health: 85,
    strength: 11,
    attack: 14,
    speed: 12,
    super_power: 'DodgeNdTailLash',
    file_url: '/models/d-wolf.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 420,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_VORTEXARCHER',
    playerId: 'PLAYER_ID_VORTEXARCHER',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 12,
    stringId: 'luna-empress',
    name: 'Luna Empress',
    avatarUrl: { file_url: "images/luna.gif" },
    description: 'A relentless warrior with unbreakable iron will and strength.',
    health: 130,
    strength: 18,
    attack: 14,
    speed: 6,
    super_power: 'Adaptability',
    file_url: '/models/luna.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 470,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_IRONBERSERKER',
    playerId: 'PLAYER_ID_IRONBERSERKER',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 13,
    stringId: 'blaze',
    name: 'Blaze',
    avatarUrl: { file_url: "images/blaze.gif" },
    description: 'A powerful sorceress with the ability to conjure lunar magic and control the tides.',
    health: 90,
    strength: 11,
    attack: 13,
    speed: 9,
    super_power: 'HeadCrush',
    file_url: '/models/blaze.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 440,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_LUNARWITCH',
    playerId: 'PLAYER_ID_LUNARWITCH',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 14,
    stringId: 'techno-mage',
    name: 'Techno Mage',
    avatarUrl: { file_url: "images/techno.gif" },
    description: 'A god of thunder, capable of summoning devastating storms.',
    health: 110,
    strength: 12,
    attack: 15,
    speed: 8,
    super_power: 'SleepSong',
    file_url: '/models/techno.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 460,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_THUNDERLORD',
    playerId: 'PLAYER_ID_THUNDERLORD',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 15,
    stringId: 'berzerker',
    name: 'Berzerker',
    avatarUrl: { file_url: "images/berzerker.gif" },
    description: 'A reborn fighter with the ability to regenerate and summon flames.',
    health: 120,
    strength: 14,
    attack: 15,
    speed: 7,
    super_power: 'Earthquake',
    file_url: '/models/berzerker.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 490,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_PHOENIXSOUL',
    playerId: 'PLAYER_ID_PHOENIXSOUL',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 16,
    stringId: 'gorgon',
    name: 'Gorgon',
    avatarUrl: { file_url: "images/gorgon.gif" },
    description: 'A swift and deadly avian warrior with the power of lightning.',
    health: 90,
    strength: 10,
    attack: 12,
    speed: 14,
    super_power: 'VineWhip',
    file_url: '/models/gorgon.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 430,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_LIGHTNINGHAWK',
    playerId: 'PLAYER_ID_LIGHTNINGHAWK',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 17,
    stringId: 'troll',
    name: 'Troll',
    avatarUrl: { file_url: "images/troll.gif" },
    description: 'A mage who draws on dark magic to wreak havoc in battle.',
    health: 100,
    strength: 11,
    attack: 13,
    speed: 10,
    super_power: 'InvisibleClaws',
    file_url: '/models/troll.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 440,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_DARKMAGE',
    playerId: 'PLAYER_ID_DARKMAGE',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 18,
    stringId: 'drake-fire',
    name: 'Drake Fire',
    avatarUrl: { file_url: "images/drake.gif" },
    description: 'A knight empowered by the sun to unleash solar beams and defend the realm.',
    health: 105,
    strength: 12,
    attack: 14,
    speed: 9,
    super_power: 'ShadowBall',
    file_url: '/models/drake.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 460,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_SOLARKNIGHT',
    playerId: 'PLAYER_ID_SOLARKNIGHT',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 19,
    stringId: 'stone-golem',
    name: 'Stone Golem',
    avatarUrl: { file_url: "images/s-golem.gif" },
    description: 'A sorcerer who wields forbidden crimson magic to unleash devastating spells.',
    health: 95,
    strength: 12,
    attack: 16,
    speed: 8,
    super_power: 'Flamethrower',
    file_url: '/models/s-golem.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 480,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_CRIMSONSORCERER',
    playerId: 'PLAYER_ID_CRIMSONSORCERER',
    createdAt: new Date(),
    experience: 0,
  },
  {
    id: 20,
    stringId: 'serena-hawk',
    name: 'Serena Hawk',
    avatarUrl: { file_url: "images/s-hawk.gif" },
    description: 'A master swordsman who strikes from the shadows, leaving his enemies in fear.',
    health: 105,
    strength: 16,
    attack: 14,
    speed: 11,
    super_power: 'ShadowBall',
    file_url: '/models/s-hawk.glb',
    animations: [
      { name: "Idle", file_url: "/animations/Idle.fbx" },
      { name: "Ready", file_url: "/animations/F-Idle.fbx" },
      { name: "flex", file_url: "/animations/flex.fbx" },
      { name: "Attack", file_url: "/animations/attack.fbx" },
      { name: "Attack 1", file_url: "/animations/attack1.fbx" },
      { name: "Walking", file_url: "/animations/Walking.fbx" },
      { name: "Running", file_url: "/animations/Running.fbx" },
    ],
    total_battles: 0,
    total_wins: 0,
    total_losses: 0,
    price: 490,
    owner: '677d1b6f4cc2b488494a2b7e',
    mintAddress: 'MINT_ADDRESS_SHADOWSWORDSMAN',
    playerId: 'PLAYER_ID_SHADOWSWORDSMAN',
    createdAt: new Date(),
    experience: 0,
  }
];
